### ISSUE TITLE
Community Fly-out Menu seems to hide itself unless you move your cursor through the desired path.

### ISSUE THREAD

**Issue by shivankacker** [ohcnetwork/landing#10]

**Comment by thecodephilic-guy** [comment]
I have worked on this issue and made it such that dropdown opens while hover on Cummunity nav link and remains open untill you click outsite the dropdown.
Here is the video link to the working solution: https://www.loom.com/share/575e841ffb6748b0b8489313b5855adb?sid=fc8a4e45-551f-48ee-8e74-f42b87e4c30f

Review it and let me if anything else needed to be fixed
