### ISSUE TITLE
Remove broken github constellation banner

### ISSUE THREAD

**Issue by sainak** [ohcnetwork/landing#23]
the github constellation page is constantly updating, so the below link is now broken
https://github.com/ohcnetwork/landing/blob/02da173f725887780f6df6ca9f977b9a31a6b6ac/pages/index.js#L149-L152

**Comment by nithish1018** [comment]
@sainak What's the expected behaviour of this issue?

**Comment by sainak** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/46787056?s=64&amp;u=30804cfeb8efc4200cf2f966d0a38103ea170dca&amp;v=4">@sainak](https://github.com/sainak) What's the expected behaviour of this issue?

set the value to {}

**Comment by nithish1018** [comment]
But that **read more** text won't redirect to any page right?,
is that's how we want that to work now?

**Comment by nithish1018** [comment]
@sainak Should I remove the read more text as well?

**Comment by sainak** [comment]
@nithish1018 {} is a truthy value in js so that still shows the readme text, instead of {} we should set it to null
