### ISSUE TITLE
Fix image widths on care product page

### ISSUE THREAD

**Issue by sainak** [ohcnetwork/landing#24]
the image sizes are too big which is causing the text to cut off

https://ohc.network/care
![Image](https://github.com/user-attachments/assets/96308abf-1c05-4342-9137-ad8e825c9976)

inspecting the element shows that the computed sizes are different than what is specified on the element
![Image](https://github.com/user-attachments/assets/ff895c1e-cbc1-4329-9bae-178bc4452222)

**Comment by IndySeh** [comment]
Hi! I'd like to work on this issue. Could you please assign it to me?
