### ISSUE TITLE
Text in 'Committed to Openness' Section is Hard to Read Due to Low Contrast

### ISSUE THREAD

**Issue by shantanuk7** [ohcnetwork/landing#26]
On the landing page, the "Committed to Openness" section has low contrast between the text (light grey/white) and the background, making it unreadable. The issue is particularly severe for the title text, where phrases like "Committed to" and "from Day One" are almost invisible.  

![Image](https://github.com/user-attachments/assets/f1d71051-6bf3-4dbd-9263-f40170249e39)

Additionally, the GitHub logo used in this section violates GitHub's branding guidelines, which allow only black or white logos ([reference](https://github.com/logos)).

**Suggested Solution:**  
- Increase the text contrast to meet WCAG 2.1 AA standards for accessibility.
- Replace the GitHub logo with a compliant black or white version.

According to WebAIM - Web Accessibility's  Contrast Checker Tool: https://webaim.org/resources/contrastchecker/?fcolor=D1D5DB&bcolor=FFFFFF The current text-background contrast ratio is 1.47:1, which fails WCAG AA standards. The suggested fix improves it to 4.83:1.

Until a better UI design is implemented, here's a proposed interim fix:
![Proposed Fix Screenshot](https://github.com/user-attachments/assets/f1189d77-2229-460e-a304-4f9a43830072)

If this solution seems acceptable, I'd be happy to work on this. Please assign the issue to me.

**Comment by mdaatifayman786** [comment]
I want to work on this. Can you assign me?

**Comment by mdaatifayman786** [comment]
I want to work on this. Can you assign me? @bodhish @sainak

**Comment by mdaatifayman786** [comment]
- It's already done, so close this issue

**Comment by shantanuk7** [comment]
The issue, it seems, still persists. I have researched more and found that the dark mode looks good but it is not working in Google Chrome browser. It works on Firefox (When user theme preferences have been set to dark theme). However, it seems to be a separate issue. 

> [@shantanuk7](https://github.com/shantanuk7) thanks for the issue. Do you want to take it up?

@bodhish @sainak I apologise for not replying earlier. **I’d be happy to work on resolving the light mode issue if it’s still available for contribution.**

**Comment by nithish1018** [comment]
@bodhish @sainak Can I work on this issue and make it look like this irrespective of light mode or dark mode?
 
![Image](https://github.com/user-attachments/assets/11f13931-30d6-4839-828f-9d16e3076598)

**Comment by rithviknishad** [comment]
Yup

**Comment by nithish1018** [comment]
> Yup

Ok, I'll raise the PR, please assign the issue to me
