### ISSUE TITLE
Slow animation speed

### ISSUE THREAD

**Issue by PAVAN507-STAR** [ohcnetwork/landing#29]
The transition animation from community to products and vice versa is slow ,that when switching the re -rendering is kind of visible .
EasyFix:decrease the transition time in the code

Screen Recording

https://github.com/user-attachments/assets/9e5b03a5-8eb6-4e6b-87c6-89b53af9ac18

If this is considered as an issue.I would like to fix this issue.

**Comment by YASHSHAH-create** [comment]
Assign me this issue

**Comment by shivankacker** [comment]
@PAVAN507-STAR I think the current animation is fast enough, anything faster would not give the same effect 👀
