### ISSUE TITLE
Setup a Timeline Page for OHC Website

### ISSUE THREAD

**Issue by aravindm4** [ohcnetwork/landing#37]
Objective

Create a timeline page on the [OHC website](https://ohc.network/) to showcase the journey and evolution of CARE, highlighting key milestones, achievements, and updates over time.

Content

The content for the timeline page is documented [here](https://ohcnetwork.notion.site/Setup-a-Timeline-Page-for-OHC-a6e3489475d942adb5a9c2bf6dca1c4c)

Requirements

1. Page Design:

- A visually engaging layout, suitable for presenting chronological events.
- Include a vertical or horizontal timeline design with expandable sections for details.

2. Implementation:

- Use a responsive design framework to ensure the page works well on all devices.
- Integrate the timeline into the existing website structure, with a link in the navigation menu.

3. Styling:

- Maintain consistency with the current OHC website’s visual theme and branding.
- Use appropriate colors, fonts, and animations for user-friendly interaction.
- Include icons or visuals for major events to enhance readability and engagement.

**Comment by DonXavierdev** [comment]
Can you please assign this to me

**Comment by awaiskhan21** [comment]
Hey i would love to work on this @aravindm4 can you assign it to me

**Comment by Tanuj1718** [comment]
@aravindm4 @rithviknishad @bodhish Would like to work on this. Can you please assign it to me?
