### ISSUE TITLE
Mention ABDM & HCX Compliance in the Landing Page

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/landing#6]
**Describe the bug**

CARE is ABDM & HCX Compliance software, but we never mention it anywhere in the landing page

Visit: https://ohc.network/

**Expected behavior**

add adbm & HCX compliance mentioning in the landing page, in the EOD call share the mockup before start coding on it

**Comment by gigincg** [comment]
@nihal467 Please file Landing Page Issues here

**Comment by sainak** [comment]
@nihal467 can you check again seem like it is already mentioned at the end of this page https://ohc.network/care

**Comment by shivankacker** [comment]
@nihal467 ABDM and HXC are mentioned here now https://ohc.network/care . Closing this issue.
